package commands

import (
	"context"
	"strings"

	"github.com/outplane/cli/internal/api"
	"github.com/outplane/cli/internal/clierr"
	"github.com/outplane/cli/internal/core"
	"github.com/outplane/cli/internal/output"
)

func init() {
	register("db role list", dbRoleList)
	register("db role create", dbRoleCreate)
	register("db role delete", dbRoleDelete)
	register("db database list", dbSchemaList)
	register("db database create", dbSchemaCreate)
	register("db database delete", dbSchemaDelete)
}

// What lives inside a managed instance: logins, and places to put tables.
//
// Every command here takes the instance first, as every other db command does,
// and then the thing inside it. One endpoint on the server creates either kind,
// told apart by which fields are sent; they are two commands because a role is
// a credential and a database is storage, and confusing them at a terminal is
// how somebody deletes the wrong one.

func dbRoleList(ctx context.Context, req Request) (output.Table, error) {
	db, roles, _, err := readContents(ctx, req)
	if err != nil {
		return output.Table{}, err
	}

	table := output.Table{Columns: []string{"name"}, Total: len(roles)}
	for _, r := range roles {
		table.Rows = append(table.Rows, map[string]any{"name": r.Name, "db": db.Name})
	}
	if len(roles) == 0 {
		table.Footer = db.Name + " is " + db.Status + " and reports no roles yet."
	}
	return table, nil
}

func dbSchemaList(ctx context.Context, req Request) (output.Table, error) {
	db, _, schemas, err := readContents(ctx, req)
	if err != nil {
		return output.Table{}, err
	}

	table := output.Table{Columns: []string{"name", "owner"}, Total: len(schemas)}
	for _, s := range schemas {
		table.Rows = append(table.Rows, map[string]any{
			"name": s.Name, "owner": nilIfEmpty(s.Owner), "db": db.Name,
		})
	}
	return table, nil
}

// dbRoleCreate adds a login.
//
// The password is generated by the provider and never returned here. It reaches
// the caller through the connection string, which is the only place it appears.
func dbRoleCreate(ctx context.Context, req Request) (output.Table, error) {
	db, name, err := instanceAndName(ctx, req, "role", "create")
	if err != nil {
		return output.Table{}, err
	}

	client, err := req.CLI.APIClient()
	if err != nil {
		return output.Table{}, err
	}

	if req.CLI.DryRun {
		req.CLI.Out.Note("Would add the role %s to %s. Nothing was sent.", name, db.Name)
		return accessTable("role", name, db, "", false), nil
	}

	if err := core.CreateDBRole(ctx, client, db.ID, name); err != nil {
		return output.Table{}, err
	}

	req.CLI.Out.Note("Added the role %s to %s.", name, db.Name)
	req.CLI.Out.Note("Its password is only in the connection string: outplane db url %s --role %s",
		db.Name, name)
	return accessTable("role", name, db, "", true), nil
}

// dbSchemaCreate adds a database, which needs an owner.
func dbSchemaCreate(ctx context.Context, req Request) (output.Table, error) {
	db, name, err := instanceAndName(ctx, req, "database", "create")
	if err != nil {
		return output.Table{}, err
	}

	client, err := req.CLI.APIClient()
	if err != nil {
		return output.Table{}, err
	}

	owner, err := resolveOwner(ctx, req, client, db)
	if err != nil {
		return output.Table{}, err
	}

	if req.CLI.DryRun {
		req.CLI.Out.Note("Would add the database %s to %s, owned by %s. Nothing was sent.",
			name, db.Name, owner)
		return accessTable("database", name, db, owner, false), nil
	}

	if err := core.CreateDBSchema(ctx, client, db.ID, name, owner); err != nil {
		return output.Table{}, err
	}

	req.CLI.Out.Note("Added the database %s to %s, owned by %s.", name, db.Name, owner)
	return accessTable("database", name, db, owner, true), nil
}

// resolveOwner picks the role that will own a new database, or asks.
//
// With one role there is nothing to choose. With several, choosing for somebody
// is choosing who can read their data.
func resolveOwner(ctx context.Context, req Request, client *api.Client, db core.Database) (string, error) {
	if owner := strings.TrimSpace(req.Flags.String("owner")); owner != "" {
		return owner, nil
	}

	roles, _, err := core.DatabaseContents(ctx, client, db.ID)
	if err != nil {
		return "", err
	}
	if len(roles) == 1 {
		return roles[0].Name, nil
	}
	return "", mustChoose("owner", roleNames(roles), db.Name)
}

func dbRoleDelete(ctx context.Context, req Request) (output.Table, error) {
	return deleteInside(ctx, req, "role")
}

func dbSchemaDelete(ctx context.Context, req Request) (output.Table, error) {
	return deleteInside(ctx, req, "database")
}

// deleteInside removes a role or a database, behind the usual protocol.
//
// Destructive for both, and the reasons differ: a database takes its tables
// with it, and a role takes away the access of everything still connecting as
// it. Neither is recoverable by the platform.
func deleteInside(ctx context.Context, req Request, kind string) (output.Table, error) {
	db, name, err := instanceAndName(ctx, req, kind, "delete")
	if err != nil {
		return output.Table{}, err
	}

	client, err := req.CLI.APIClient()
	if err != nil {
		return output.Table{}, err
	}

	if req.CLI.DryRun {
		req.CLI.Out.Note("The %s %s in %s would be destroyed.", kind, name, db.Name)
		return accessTable(kind, name, db, "", false), nil
	}

	if err := checkInsideConfirmed(req, kind, name, db); err != nil {
		return output.Table{}, err
	}

	if kind == "role" {
		err = core.DeleteDBRole(ctx, client, db.ID, name)
	} else {
		err = core.DeleteDBSchema(ctx, client, db.ID, name)
	}
	if err != nil {
		return output.Table{}, err
	}

	req.CLI.Out.Note("Deleted the %s %s from %s.", kind, name, db.Name)
	return accessTable(kind, name, db, "", true), nil
}

func checkInsideConfirmed(req Request, kind, name string, db core.Database) error {
	confirm := func(hint string, args ...any) error {
		return clierr.New(clierr.KindConfirmation, "deleting %s needs confirmation", name).
			WithCode("confirmation.required").
			WithHint(hint, args...).
			WithConfirmCommand("outplane", "db", kind, "delete", db.Name, name,
				"--yes", "--confirm-name", name)
	}

	if harness := req.CLI.Exec.AgentHarness; harness != "" {
		return confirm("This is running under %s, where the CLI cannot be the thing that "+
			"approves destroying data. Hand the command below to whoever is accountable "+
			"for it.", harness)
	}

	if !req.Flags.Bool("yes") || req.Flags.String("confirm-name") == "" {
		if kind == "role" {
			return confirm("Deleting the role %s breaks everything still connecting as it. "+
				"Both --yes and --confirm-name are required.", name)
		}
		return confirm("Deleting the database %s destroys its tables, and nothing restores "+
			"them. Both --yes and --confirm-name are required.", name)
	}

	if given := req.Flags.String("confirm-name"); given != name {
		return clierr.New(clierr.KindUsage,
			"--confirm-name says %q and the %s is called %q", given, kind, name).
			WithCode("db.confirm_name_mismatch").
			WithDetail("expected", name).
			WithDetail("given", given)
	}
	return nil
}

// instanceAndName reads the two positionals every command here takes: which
// instance, and which thing inside it.
func instanceAndName(ctx context.Context, req Request, kind, verb string) (core.Database, string, error) {
	db, err := targetDatabase(ctx, req, "get")
	if err != nil {
		return core.Database{}, "", err
	}

	if len(req.Args) < 2 || strings.TrimSpace(req.Args[1]) == "" {
		return core.Database{}, "", clierr.New(clierr.KindUsage, "no %s name given", kind).
			WithCode("usage.missing_argument").
			WithStep(verb+" one", "outplane", "db", kind, verb, db.Name, "<NAME>")
	}
	return db, req.Args[1], nil
}

// readContents resolves the instance and reads what is in it.
func readContents(ctx context.Context, req Request) (core.Database, []core.DBRole, []core.DBSchema, error) {
	db, err := targetDatabase(ctx, req, "get")
	if err != nil {
		return core.Database{}, nil, nil, err
	}

	client, err := req.CLI.APIClient()
	if err != nil {
		return core.Database{}, nil, nil, err
	}

	roles, schemas, err := core.DatabaseContents(ctx, client, db.ID)
	if err != nil {
		return core.Database{}, nil, nil, err
	}
	return db, roles, schemas, nil
}

func accessTable(kind, name string, db core.Database, owner string, changed bool) output.Table {
	return output.Table{
		Single:  true,
		Columns: []string{"kind", "name", "db", "changed"},
		Total:   1,
		Rows: []map[string]any{{
			"kind":    kind,
			"name":    name,
			"db":      db.Name,
			"dbId":    db.ID,
			"owner":   nilIfEmpty(owner),
			"changed": changed,
		}},
	}
}
